package CIF::SDK::Format::Bind;

use strict;
use warnings;

use Mouse;

with 'CIF::SDK::Format';

use constant FILENAME_DEFAULT => '/etc/namedb/';

sub understands {
    my $self = shift;
    my $args = shift;

    return unless($args->{'format'});
    return 1 if($args->{'format'} eq 'bind');
}

sub process {
    my $self = shift;
    my $data = shift;
    my $args = shift;
    
    my $filename = $args->{'filename'} || FILENAME_DEFAULT;

    my @text = (
        '// generated by: ' . $0 . ' at ' . time()
    );
    
    foreach my $d (@$data){
        next unless($d->{'otype'} =~ /^fqdn$/);
        my $t = 'zone "' . $d->{'observable'} . '" {type master; file "' . $filename . '";};';   
        push(@text, $t);
    }
    return join("\n",@text);
}

__PACKAGE__->meta()->make_immutable();

1;
